"""Content-addressed float32 embedding cache in its own SQLite file.

A derived, disposable replay store: every vector here can be regenerated by the
remote embedding endpoint, so it is never authoritative. Offline runs use
``require_all`` to replay cached vectors and fail on any miss instead of calling
a provider. This module contains no network code.

Key = sha256(model_id \\0 kind \\0 instruction \\0 text), so the same text embedded
as a document, as a query, under another instruction, or by another model never
collides.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from pathlib import Path
from typing import Dict, Iterable, List, NamedTuple, Sequence, Tuple, Union

import numpy as np

KINDS = ("doc", "query")
_SQL_CHUNK = 500  # stays under SQLite's host-parameter limit


class CacheItem(NamedTuple):
    """One text to embed, with the role and instruction that change its vector."""

    kind: str
    text: str
    instruction: str = ""


def cache_key(model_id: str, kind: str, instruction: str, text: str, style: str = "qwen3") -> str:
    """sha256 of the exact string the embedder receives, bound to the model.

    Queries are keyed on their formatted text (instruction + style), so two
    items collide only if the provider would see identical input. JSON
    encoding keeps field boundaries unambiguous.
    """
    if kind not in KINDS:
        raise ValueError(f"cache kind must be one of {KINDS}, got {kind!r}")
    from engine.embedding import format_query_for_embedding

    embedded = format_query_for_embedding(text, instruction or None, style) if kind == "query" else text
    payload = json.dumps([model_id, kind, embedded], ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


class EmbeddingCacheMiss(LookupError):
    """Raised in replay mode when requested vectors are absent."""


class EmbeddingCache:
    """Validated vector cache bound to one model id and one vector width."""

    def __init__(self, path: Union[str, Path], model_id: str, expected_dim: int, query_style: str = "qwen3"):
        if not model_id:
            raise ValueError("model_id must be non-empty")
        if expected_dim < 1:
            raise ValueError("expected_dim must be positive")
        self.path = Path(path)
        self.model_id = model_id
        self.query_style = query_style
        self.expected_dim = int(expected_dim)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._conn = sqlite3.connect(str(self.path))
        with self._conn:
            self._conn.execute(
                """CREATE TABLE IF NOT EXISTS embedding_cache (
                       key TEXT PRIMARY KEY,
                       model_id TEXT NOT NULL,
                       dim INTEGER NOT NULL,
                       vector BLOB NOT NULL
                   )"""
            )

    def key(self, item: CacheItem) -> str:
        return cache_key(self.model_id, item.kind, item.instruction, item.text, self.query_style)

    def _validate(self, vector, label: str) -> np.ndarray:
        vec = np.asarray(vector, dtype=np.float32)
        if vec.ndim != 1 or vec.shape[0] != self.expected_dim:
            raise ValueError(
                f"{label} has shape {vec.shape}; cache requires exactly ({self.expected_dim},)"
            )
        if not np.all(np.isfinite(vec)):
            raise ValueError(f"{label} contains non-finite values")
        return vec

    def get_many(self, items: Iterable[CacheItem]) -> Tuple[Dict[str, np.ndarray], List[CacheItem]]:
        """Return ({key: vector} for hits, [items that missed]) in input order."""
        items = list(items)
        keys = [self.key(item) for item in items]
        unique = list(dict.fromkeys(keys))
        found: Dict[str, np.ndarray] = {}
        for start in range(0, len(unique), _SQL_CHUNK):
            chunk = unique[start:start + _SQL_CHUNK]
            rows = self._conn.execute(
                f"SELECT key, model_id, dim, vector FROM embedding_cache "
                f"WHERE key IN ({','.join('?' * len(chunk))})",
                chunk,
            ).fetchall()
            for key, model_id, dim, blob in rows:
                # A corrupt or foreign row fails loudly; it is never skipped.
                if model_id != self.model_id or dim != self.expected_dim:
                    raise ValueError(
                        f"cache row {key[:12]} is ({model_id!r}, dim={dim}); "
                        f"expected ({self.model_id!r}, dim={self.expected_dim})"
                    )
                if len(blob) != dim * 4:
                    raise ValueError(f"cache row {key[:12]} has {len(blob)} bytes; expected {dim * 4}")
                found[key] = self._validate(np.frombuffer(blob, dtype="<f4").copy(), f"cache row {key[:12]}")
        missing = [item for item, key in zip(items, keys) if key not in found]
        return found, missing

    def put_many(self, items: Sequence[CacheItem], vectors: Sequence) -> int:
        """Validate every vector, then insert atomically. Returns rows inserted.

        First write wins: an existing key is left untouched so earlier replays
        stay reproducible even if the provider is nondeterministic.
        """
        if len(items) != len(vectors):
            raise ValueError(f"{len(items)} items but {len(vectors)} vectors")
        rows = [
            (self.key(item), self.model_id, self.expected_dim,
             self._validate(vector, f"vector for {item.kind} item {index}").astype("<f4").tobytes())
            for index, (item, vector) in enumerate(zip(items, vectors))
        ]
        with self._conn:
            before = self._conn.total_changes
            self._conn.executemany(
                "INSERT OR IGNORE INTO embedding_cache (key, model_id, dim, vector) VALUES (?, ?, ?, ?)",
                rows,
            )
            return self._conn.total_changes - before

    def require_all(self, items: Iterable[CacheItem]) -> Dict[str, np.ndarray]:
        """Replay mode: return every vector or raise ``EmbeddingCacheMiss``."""
        items = list(items)
        found, missing = self.get_many(items)
        if missing:
            kinds = sorted({item.kind for item in missing})
            raise EmbeddingCacheMiss(
                f"embedding cache miss: {len(missing)} of {len(items)} items absent "
                f"(model_id={self.model_id!r}, kinds={kinds}, cache={self.path}); "
                "replay mode never calls a provider"
            )
        return found

    def __len__(self) -> int:
        return self._conn.execute("SELECT COUNT(*) FROM embedding_cache").fetchone()[0]

    def close(self) -> None:
        self._conn.close()

    def __enter__(self) -> "EmbeddingCache":
        return self

    def __exit__(self, *exc) -> None:
        self.close()
